### ISSUE TITLE
Android Beacon detection is not working when App close.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [Driversnote-Dev/react-native-kontaktio#53]
Hi,

I have set region and start scanning in android. it's work fine when app in foreground. The data of beacon getting the results. but when App is closed, And after I checked the beacon is not connect.

Can you help me what is mistake in android.

Thanks.

**Comment by ginixsan** [comment]
Anybody did manage to make it work for region monitoring when app is closed?

**Comment by Andruschenko** [comment]
You probably have to use an [Android Foreground Service](https://developer.android.com/guide/components/services). Take a look at this package: https://github.com/voximplant/react-native-foreground-service . I didn't yet try it myself though.

Btw, how does your definition of **closed** relate to the appstate? When you observe the [AppState](https://facebook.github.io/react-native/docs/appstate) is the app state `background`?

**Comment by nylsoo** [comment]
Thanks @Andruschenko, this seems to work fine! When using a foreground service the beacons scanner seems to keep working.

**Comment by nylsoo** [comment]
There stil seems to be a problem with detecting beacons in the background on android. When your screen is turned off no beacons are updated. This seems to be a bug in the Kontakt SDK. I have made an issue for Kontakt ([#201](https://github.com/kontaktio/kontakt-android-sdk/issues/201)).

**Comment by unkindypie** [comment]
@nylsoo did you find the solution of this problem? I am currently facing the same issue using react-native-beacons-manager and the same foreground service as you.

**Comment by unkindypie** [comment]
@nylsoo nevermind. I figured out by myself. Just updated version of altbeacons to the latest. react-native-beacons-manager from npm for some reason uses old build from 2017. Installing from their github repository directly will fix this issue.

**Comment by izaa** [comment]
@unkindypie Hi, could you tell what version the react-native-beacons-manager exactly should use and where do you change the version? Thanks :)

**Comment by unkindypie** [comment]
@izaa just use `npm install https://git@github.com/MacKentoch/react-native-beacons-manager` to install the package from the latest commit at master. But I should say that it works perfectly on android >=8.1 including background, but for some reason stops detecting beacons on android <8.1. I tried some older commits from that repository and faced the same problem. If you find a solution, please share it.

**Comment by izaa** [comment]
@unkindypie  ah ok! Yes I've tried that, but looks that this kontaktio works better than that manger. How do you feel which one is better?

**Comment by unkindypie** [comment]
@izaa in my opinion currenly both of them are bad for android. I have created an issue on react-native-beacons-manager, maybe someday someone will help us.

**Comment by izaa** [comment]
@unkindypie thanks for the info! So both work better in iOS? I haven't tried yet iOS.

**Comment by nylsoo** [comment]
I am currently contacting Kontakt to see if they could do something about this issue. They seem to be unresponsive on their own Github page.

**Comment by nylsoo** [comment]
Got in contact with the Kontakt support desk and it seems this issue won't be fixed any time soon due to lack of mobile developers... They recommended using another library like [Alt Beacon](https://github.com/AltBeacon/android-beacon-library).



Their response: 
Hi ....,
Unfortunately as of right now, we can not assure that this feature will be implemented in the Android SDK. It has been noted but it will not be implemented in the near future because of the availability of our mobile developers.
Solution, for now, would be using foreground services in Android and some other libraries that fit your needs as you mentioned before.I hope you understandBest regards, | Hi Niels,Unfortunately as of right now, we can not assure that this feature will be implemented in the Android SDK. It has been noted but it will not be implemented in the near future because of the availability of our mobile developers.Solution, for now, would be using foreground services in Android and some other libraries that fit your needs as you mentioned before.
I hope you understand
Best regards,
