### ISSUE TITLE
"didDiscoverDevices" not being triggered on iOS

### ISSUE THREAD

**Issue by jazg** [Driversnote-Dev/react-native-kontaktio#71]
I've followed the instructions from the example, but for whatever reason the `didDiscoverDevices` event is not being triggered on iOS. I'm using my Mac to simulate a beacon (have tried both the BeaconEmitter and MactsAsBeacon apps). I'm running iOS 13.4 and version 0.61.5 of React Native.

Let me know if there's anything I might've missed. Thanks!

**Comment by Andruschenko** [comment]
Did you use the code from this minimal example in the README? https://github.com/Driversnote-Dev/react-native-kontaktio#minimal-example

The example app is unfortunately outdated.

**Comment by jazg** [comment]
Thanks for the prompt response!

Yes, I'm just trying to run the minimal example. Does it matter what UUID/Identifier I use in the Mac beacon simulator app?

**Comment by jazg** [comment]
@Andruschenko

**Comment by Andruschenko** [comment]
The UUID shouldn't matter in the example. I tested the new minimal example code with a Kontakt.io beacon. Do you have the chance to try with a Kontakt.io beacon?

In the past I tested the MactsAsBeacon app and it worked. I just didn't test the new code with it.

Otherwise it's hard for me to help here.

**Comment by jazg** [comment]
@andrekovac Thanks, I got it working with the beacon simulator! Should it be able to detect beacons in the background on iOS?
